### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by ChrisEdBurt**
Additional grammar fixes.

### CODE REVIEW

**Comment by thindil** [comment]
Nice as usual :) Thank you very much for your work. Just one thing - don't try to fix the code documentation in the directory `doc` (i mean this HTML files). It is auto-generated from the code thus you work may be soon or later lost when it will be regenerated again ;)

**Comment by ChrisEdBurt** [comment]
Ah really, I see,  I will keep that in mind for any future updates.

**Comment by ChrisEdBurt** [comment]
I have a question about the strength of the different ammo types.

The descriptions for most of the ammo says "upgraded ammo type", in my opinion, that isn't the easiest way to tell the ammo strengths apart, at least at a glance.

Would it be simpler to say standard ammunition, advanced, ammunition, superior ammunition, etc.. or would you prefer "1.5/2.0/2.5 times stronger than standard ammunition" ?

**Comment by thindil** [comment]
Yes, most of current descriptions are "placeholders" which need to upgrade. I think standard/advanced/superior things is the best. The players can see difference if they enable proper option in the game options.

**Pull request merged**
